CREATE TABLE IF NOT EXISTS access_log (
    id              BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id         BIGINT       NULL,
    client_id       VARCHAR(64)  NOT NULL,
    ip_address      VARCHAR(64)  NULL,
    user_agent      VARCHAR(512) NULL,
    device_type     VARCHAR(32)  NULL,
    access_type     VARCHAR(32)  NOT NULL DEFAULT 'WEB',
    page_path       VARCHAR(512) NULL,
    referrer        VARCHAR(512) NULL,
    locale          VARCHAR(32)  NULL,
    timezone        VARCHAR(64)  NULL,
    screen_width    INT          NULL,
    screen_height   INT          NULL,
    viewport_width  INT          NULL,
    viewport_height INT          NULL,
    connection_type VARCHAR(32)  NULL,
    latitude        DECIMAL(10, 7) NULL,
    longitude       DECIMAL(10, 7) NULL,
    gps_accuracy    DECIMAL(10, 2) NULL,
    gps_status      VARCHAR(32)  NULL,
    extra_json      JSON         NULL,
    created_at      DATETIME(6)  NOT NULL,
    INDEX idx_access_log_created_at (created_at),
    INDEX idx_access_log_user_id (user_id),
    INDEX idx_access_log_client_id (client_id),
    INDEX idx_access_log_ip (ip_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
